export { default as ManageEntityTags } from './components/ManageEntityTags';
export { default as WithSearchTags } from './components/WithSearchTags';
export { default as WithUpdateEntityTags } from './components/WithUpdateEntityTags';
export { default as WithTags } from './components/WithTags';
export { default as withTagActions } from './hoc/withTagActions';
export { default as withTags } from './hoc/withTags';
export { requestTags } from './actions/requestTags';
export { updateTag } from './actions/updateTag';
export * from './actions/updateTagCollection';
export * from './services/getTagLabel';
