FROM golang

RUN go get -u github.com/kardianos/govendor
RUN go install github.com/kardianos/govendor

ADD . /go/src/github.com/CaliOpen/Caliopen/src/backend
WORKDIR /go/src/github.com/CaliOpen/Caliopen/src/backend

RUN govendor sync -v
RUN go install github.com/CaliOpen/Caliopen/src/backend/protocols/go.imap/cmd/imapworker
RUN go install github.com/CaliOpen/Caliopen/src/backend/protocols/go.imap/cmd/imapctl

WORKDIR /go/src/github.com/CaliOpen/Caliopen/src/backend/configs
ENTRYPOINT imapworker start -c caliopen-imap-worker --configpath /etc/caliopen
