FROM golang

RUN go get -u github.com/kardianos/govendor
RUN go install github.com/kardianos/govendor

ADD . /go/src/github.com/CaliOpen/Caliopen/src/backend
WORKDIR /go/src/github.com/CaliOpen/Caliopen/src/backend

RUN govendor sync -v
RUN go build github.com/CaliOpen/Caliopen/src/backend/protocols/go.smtp/cmd/caliopen_lmtpd

WORKDIR /go/src/github.com/CaliOpen/Caliopen/src/backend/configs
ENTRYPOINT ../caliopen_lmtpd serve -c /etc/caliopen/lmtp

EXPOSE 2525
