FROM golang

RUN go get -u github.com/kardianos/govendor
RUN go install github.com/kardianos/govendor

ADD . /go/src/github.com/CaliOpen/Caliopen/src/backend
WORKDIR /go/src/github.com/CaliOpen/Caliopen/src/backend

RUN govendor sync -v
RUN go install github.com/CaliOpen/Caliopen/src/backend/workers/go.remoteIDs/cmd/idpoller

WORKDIR /go/src/github.com/CaliOpen/Caliopen/src/backend/configs
ENTRYPOINT idpoller start
