FROM golang

RUN go get -u github.com/kardianos/govendor
RUN go install github.com/kardianos/govendor

ADD . /go/src/github.com/CaliOpen/CaliOpen/src/backend
WORKDIR /go/src/github.com/CaliOpen/CaliOpen/src/backend

RUN govendor sync -v
RUN go build github.com/CaliOpen/CaliOpen/src/backend/interfaces/REST/go.server/cmd/caliopen_rest

WORKDIR /go/src/github.com/CaliOpen/CaliOpen/src/backend/configs
ENTRYPOINT ../caliopen_rest serve -c caliopen-api.docker

EXPOSE 31415
