FROM golang

RUN go get -u github.com/kardianos/govendor
RUN go install github.com/kardianos/govendor

ADD . /go/src/github.com/CaliOpen/Caliopen/src/backend
WORKDIR /go/src/github.com/CaliOpen/Caliopen/src/backend

RUN govendor sync -v
RUN go build github.com/CaliOpen/Caliopen/src/backend/interfaces/REST/go.server/cmd/caliopen_rest

WORKDIR /go/src/github.com/CaliOpen/Caliopen/src/backend/configs
ENTRYPOINT ../caliopen_rest serve -c apiv2 --configpath /etc/caliopen

EXPOSE 31415
