@startuml
hide footbox
title Inbound SMTP closeup
box "SMTPd"
participant "go.smtpd" as smtpd
endbox
database cassandra
database elasticsearch
box "message platform"
participant "NATS server" as nats
endbox
box "interface NATS"
control "py.nats" as pynats
endbox
box "Caliopen Main"
control "py.main" as pymain
endbox
box
[-> smtpd: smtp email
activate smtpd
smtpd --\ cassandra: recipients lookup
cassandra --/ smtpd
smtpd ->o cassandra: store raw email once
cassandra --// smtpd: raw email ID
== Repetition ==
smtpd -[#0000FF]> nats: send order "process_raw"\n to "inboundSMTP" topic\nwith msg_id & rcp_id
pynats x[#0000FF]-> nats: subscribe to "process_raw"\n on "inboundSMTP" topic
group broker operations
pynats -> pymain: UserMessageDelivery()
activate pymain
cassandra --> pymain: get raw email
activate pymain
note over pymain: delivery.py
cassandra --> pymain: get user
pymain -> pymain: unmarshall into a\n"MailMessage" intermediary representation
pymain -> pymain: "process_inbound()
deactivate pymain
group qualifier operations
note over pymain: qualifier.py
pymain -> pymain: unmarshall into a\n"NewMessage" intermediary representation
activate pymain
pymain -> pymain: basic validation/conformation
pymain -> pymain: message qualification/enrichment
end
pymain -> pymain: build a Caliopen Message
pymain ->o cassandra: store message object\n(type email)
pymain ->o elasticsearch: index message object\n(type email)
deactivate pymain
pymain -> pynats: return Message or Exception
deactivate pymain
end
pynats -[#0000FF]-> nats: reply "OK"
nats -[#0000FF]-> smtpd: reply "OK"
[<- smtpd: "250 OK"
deactivate smtpd
@enduml